FROM grafana/grafana:10.2.0

# Copiar arquivo de configuração
COPY --chown=472:0 grafana.ini /etc/grafana/grafana.ini

# Copiar provisioning
COPY --chown=472:0 provisioning /etc/grafana/provisioning

# Expor porta
EXPOSE 3000

# Comando padrão já definido na imagem base
